// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "HermesDuckDBServer.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::com::thrift::hermesduckdbserver;

class HermesDuckDBServerHandler : virtual public HermesDuckDBServerIf {
 public:
  HermesDuckDBServerHandler() {
    // Your initialization goes here
  }

  void getFreshDataHermes(std::vector<int8_t> & _return, const std::string& query, const int64_t queryCounter, const std::string& tableName) {
    // Your implementation goes here
    printf("getFreshDataHermes\n");
  }

  void printHelloHermes() {
    // Your implementation goes here
    printf("printHelloHermes\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<HermesDuckDBServerHandler> handler(new HermesDuckDBServerHandler());
  ::std::shared_ptr<TProcessor> processor(new HermesDuckDBServerProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

