/**
 * Autogenerated by Thrift Compiler (0.17.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef LogParserServer_H
#define LogParserServer_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "LogParserServer_types.h"



#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class LogParserServerIf {
 public:
  virtual ~LogParserServerIf() {}
  virtual void ping() = 0;
  virtual void shutdown() = 0;
  virtual void printHello() = 0;
  virtual void parser(Binlog& _return) = 0;
};

class LogParserServerIfFactory {
 public:
  typedef LogParserServerIf Handler;

  virtual ~LogParserServerIfFactory() {}

  virtual LogParserServerIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(LogParserServerIf* /* handler */) = 0;
  };

class LogParserServerIfSingletonFactory : virtual public LogParserServerIfFactory {
 public:
  LogParserServerIfSingletonFactory(const ::std::shared_ptr<LogParserServerIf>& iface) : iface_(iface) {}
  virtual ~LogParserServerIfSingletonFactory() {}

  virtual LogParserServerIf* getHandler(const ::apache::thrift::TConnectionInfo&) override {
    return iface_.get();
  }
  virtual void releaseHandler(LogParserServerIf* /* handler */) override {}

 protected:
  ::std::shared_ptr<LogParserServerIf> iface_;
};

class LogParserServerNull : virtual public LogParserServerIf {
 public:
  virtual ~LogParserServerNull() {}
  void ping() override {
    return;
  }
  void shutdown() override {
    return;
  }
  void printHello() override {
    return;
  }
  void parser(Binlog& /* _return */) override {
    return;
  }
};


class LogParserServer_ping_args {
 public:

  LogParserServer_ping_args(const LogParserServer_ping_args&) noexcept;
  LogParserServer_ping_args& operator=(const LogParserServer_ping_args&) noexcept;
  LogParserServer_ping_args() noexcept {
  }

  virtual ~LogParserServer_ping_args() noexcept;

  bool operator == (const LogParserServer_ping_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const LogParserServer_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const LogParserServer_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class LogParserServer_ping_pargs {
 public:


  virtual ~LogParserServer_ping_pargs() noexcept;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class LogParserServer_ping_result {
 public:

  LogParserServer_ping_result(const LogParserServer_ping_result&) noexcept;
  LogParserServer_ping_result& operator=(const LogParserServer_ping_result&) noexcept;
  LogParserServer_ping_result() noexcept {
  }

  virtual ~LogParserServer_ping_result() noexcept;

  bool operator == (const LogParserServer_ping_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const LogParserServer_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const LogParserServer_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class LogParserServer_ping_presult {
 public:


  virtual ~LogParserServer_ping_presult() noexcept;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class LogParserServer_shutdown_args {
 public:

  LogParserServer_shutdown_args(const LogParserServer_shutdown_args&) noexcept;
  LogParserServer_shutdown_args& operator=(const LogParserServer_shutdown_args&) noexcept;
  LogParserServer_shutdown_args() noexcept {
  }

  virtual ~LogParserServer_shutdown_args() noexcept;

  bool operator == (const LogParserServer_shutdown_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const LogParserServer_shutdown_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const LogParserServer_shutdown_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class LogParserServer_shutdown_pargs {
 public:


  virtual ~LogParserServer_shutdown_pargs() noexcept;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class LogParserServer_shutdown_result {
 public:

  LogParserServer_shutdown_result(const LogParserServer_shutdown_result&) noexcept;
  LogParserServer_shutdown_result& operator=(const LogParserServer_shutdown_result&) noexcept;
  LogParserServer_shutdown_result() noexcept {
  }

  virtual ~LogParserServer_shutdown_result() noexcept;

  bool operator == (const LogParserServer_shutdown_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const LogParserServer_shutdown_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const LogParserServer_shutdown_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class LogParserServer_shutdown_presult {
 public:


  virtual ~LogParserServer_shutdown_presult() noexcept;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class LogParserServer_printHello_args {
 public:

  LogParserServer_printHello_args(const LogParserServer_printHello_args&) noexcept;
  LogParserServer_printHello_args& operator=(const LogParserServer_printHello_args&) noexcept;
  LogParserServer_printHello_args() noexcept {
  }

  virtual ~LogParserServer_printHello_args() noexcept;

  bool operator == (const LogParserServer_printHello_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const LogParserServer_printHello_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const LogParserServer_printHello_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class LogParserServer_printHello_pargs {
 public:


  virtual ~LogParserServer_printHello_pargs() noexcept;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class LogParserServer_printHello_result {
 public:

  LogParserServer_printHello_result(const LogParserServer_printHello_result&) noexcept;
  LogParserServer_printHello_result& operator=(const LogParserServer_printHello_result&) noexcept;
  LogParserServer_printHello_result() noexcept {
  }

  virtual ~LogParserServer_printHello_result() noexcept;

  bool operator == (const LogParserServer_printHello_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const LogParserServer_printHello_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const LogParserServer_printHello_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class LogParserServer_printHello_presult {
 public:


  virtual ~LogParserServer_printHello_presult() noexcept;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class LogParserServer_parser_args {
 public:

  LogParserServer_parser_args(const LogParserServer_parser_args&) noexcept;
  LogParserServer_parser_args& operator=(const LogParserServer_parser_args&) noexcept;
  LogParserServer_parser_args() noexcept {
  }

  virtual ~LogParserServer_parser_args() noexcept;

  bool operator == (const LogParserServer_parser_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const LogParserServer_parser_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const LogParserServer_parser_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class LogParserServer_parser_pargs {
 public:


  virtual ~LogParserServer_parser_pargs() noexcept;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _LogParserServer_parser_result__isset {
  _LogParserServer_parser_result__isset() : success(false) {}
  bool success :1;
} _LogParserServer_parser_result__isset;

class LogParserServer_parser_result {
 public:

  LogParserServer_parser_result(const LogParserServer_parser_result&);
  LogParserServer_parser_result& operator=(const LogParserServer_parser_result&);
  LogParserServer_parser_result() noexcept {
  }

  virtual ~LogParserServer_parser_result() noexcept;
  Binlog success;

  _LogParserServer_parser_result__isset __isset;

  void __set_success(const Binlog& val);

  bool operator == (const LogParserServer_parser_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const LogParserServer_parser_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const LogParserServer_parser_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _LogParserServer_parser_presult__isset {
  _LogParserServer_parser_presult__isset() : success(false) {}
  bool success :1;
} _LogParserServer_parser_presult__isset;

class LogParserServer_parser_presult {
 public:


  virtual ~LogParserServer_parser_presult() noexcept;
  Binlog* success;

  _LogParserServer_parser_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class LogParserServerClient : virtual public LogParserServerIf {
 public:
  LogParserServerClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  LogParserServerClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping() override;
  void send_ping();
  void recv_ping();
  void shutdown() override;
  void send_shutdown();
  void recv_shutdown();
  void printHello() override;
  void send_printHello();
  void recv_printHello();
  void parser(Binlog& _return) override;
  void send_parser();
  void recv_parser(Binlog& _return);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class LogParserServerProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<LogParserServerIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) override;
 private:
  typedef  void (LogParserServerProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_shutdown(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_printHello(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_parser(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  LogParserServerProcessor(::std::shared_ptr<LogParserServerIf> iface) :
    iface_(iface) {
    processMap_["ping"] = &LogParserServerProcessor::process_ping;
    processMap_["shutdown"] = &LogParserServerProcessor::process_shutdown;
    processMap_["printHello"] = &LogParserServerProcessor::process_printHello;
    processMap_["parser"] = &LogParserServerProcessor::process_parser;
  }

  virtual ~LogParserServerProcessor() {}
};

class LogParserServerProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  LogParserServerProcessorFactory(const ::std::shared_ptr< LogParserServerIfFactory >& handlerFactory) noexcept :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) override;

 protected:
  ::std::shared_ptr< LogParserServerIfFactory > handlerFactory_;
};

class LogParserServerMultiface : virtual public LogParserServerIf {
 public:
  LogParserServerMultiface(std::vector<std::shared_ptr<LogParserServerIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~LogParserServerMultiface() {}
 protected:
  std::vector<std::shared_ptr<LogParserServerIf> > ifaces_;
  LogParserServerMultiface() {}
  void add(::std::shared_ptr<LogParserServerIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ping() override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping();
    }
    ifaces_[i]->ping();
  }

  void shutdown() override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->shutdown();
    }
    ifaces_[i]->shutdown();
  }

  void printHello() override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->printHello();
    }
    ifaces_[i]->printHello();
  }

  void parser(Binlog& _return) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->parser(_return);
    }
    ifaces_[i]->parser(_return);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class LogParserServerConcurrentClient : virtual public LogParserServerIf {
 public:
  LogParserServerConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  LogParserServerConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping() override;
  int32_t send_ping();
  void recv_ping(const int32_t seqid);
  void shutdown() override;
  int32_t send_shutdown();
  void recv_shutdown(const int32_t seqid);
  void printHello() override;
  int32_t send_printHello();
  void recv_printHello(const int32_t seqid);
  void parser(Binlog& _return) override;
  int32_t send_parser();
  void recv_parser(Binlog& _return, const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif



#endif
