// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "LogParserServer.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

class LogParserServerHandler : virtual public LogParserServerIf {
 public:
  LogParserServerHandler() {
    // Your initialization goes here
  }

  void ping() {
    // Your implementation goes here
    printf("ping\n");
  }

  void shutdown() {
    // Your implementation goes here
    printf("shutdown\n");
  }

  void printHello() {
    // Your implementation goes here
    printf("printHello\n");
  }

  void parser(Binlog& _return) {
    // Your implementation goes here
    printf("parser\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<LogParserServerHandler> handler(new LogParserServerHandler());
  ::std::shared_ptr<TProcessor> processor(new LogParserServerProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

